finish traffic-splitting test

diff --git a/.github/workflows/use-case-test-taffic-splitting.yml b/.github/workflows/use-case-test-taffic-splitting.yml
--- a/.github/workflows/use-case-test-taffic-splitting.yml
+++ b/.github/workflows/use-case-test-taffic-splitting.yml
@@ -24,10 +24,10 @@ jobs:
       - name: Install helm
         uses: Azure/setup-helm@v4
 
-      - name: Install newman
+      - name: Install Packages
         run: |
           sudo apt update && \
-          sudo apt install nodejs npm -y && \
+          sudo apt install nodejs npm hey -y && \
           npm install -g newman
 
       - name: Start Minikube
@@ -60,16 +60,13 @@ jobs:
           TYK_DATA_PLANE_SHARDING_ENABLED=true \
           TYK_DATA_PLANE_SHARDING_TAGS=${{ env.PRIMARY }} \
           GATEWAY_VERSION=${{ inputs.gateway_version }} \
-          ./up.sh --redis redis --namespace tyk-dp tyk-dp-${{ env.PRIMARY }}
+          ./up.sh --redis redis --namespace tyk-dp-${{ env.PRIMARY }} tyk-dp
 
       - name: Sleep 60 seconds
         run: sleep 60
 
       - name: Test tyk-data-plane deployment - ${{ env.PRIMARY }}
         run: newman run --folder gateway --env-var "gateway.port=${{ env.PRIMARY_PORT }}" --env-var "deployment=data-plane" tyk-k8s-demo.postman_collection.json
-
-      - name: Test httpbin API
-        run: newman run --folder operator-classic-httpbin --insecure --env-var "gateway.port=${{ env.PRIMARY_PORT }}" -n 1 tyk-k8s-demo.postman_collection.json
 
       - name: Deploy tyk-data-plane - ${{ env.SECONDARY }} - ${{ inputs.gateway_version }}
         run: |
@@ -82,16 +79,13 @@ jobs:
           TYK_DATA_PLANE_SHARDING_ENABLED=true \
           TYK_DATA_PLANE_SHARDING_TAGS=${{ env.SECONDARY }} \
           GATEWAY_VERSION=${{ inputs.gateway_version }} \
-          ./up.sh --redis redis --namespace tyk-dp tyk-dp-${{ env.SECONDARY }}
+          ./up.sh --redis redis --namespace tyk-dp-${{ env.SECONDARY }} tyk-dp
 
       - name: Sleep 60 seconds
         run: sleep 60
 
       - name: Test tyk-data-plane deployment - ${{ env.SECONDARY }}
         run: newman run --folder gateway --env-var "gateway.port=${{ env.SECONDARY_PORT }}" --env-var "deployment=data-plane" tyk-k8s-demo.postman_collection.json
-
-      - name: Test httpbin API
-        run: newman run --folder operator-classic-httpbin --insecure --env-var "gateway.port=${{ env.SECONDARY_PORT }}" -n 1 tyk-k8s-demo.postman_collection.json
 
       - name: Create APIs with 80/20 split of 1000 rate per 60
         run: |
@@ -100,14 +94,14 @@ jobs:
               -e "s/gateway_scope/${{ env.PRIMARY }}/g" \
               -e "s/rate: RATE/rate: 800/g" \
               -e "s/replace_namespace/tyk/g" \
-              .github/use-case-tests/traffic-splitting/api.yml | kubectl apply -f -n tyk -
+              .github/use-case-tests/traffic-splitting/api.yml | kubectl apply -n tyk -f -
 
           sed -e "s/api_name/httpbin-api-${{ env.SECONDARY }}/g" \
               -e "s/policy_name/httpbin-policy-${{ env.SECONDARY }}/g" \
               -e "s/gateway_scope/${{ env.SECONDARY }}/g" \
               -e "s/rate: RATE/rate: 200/g" \
               -e "s/replace_namespace/tyk/g" \
-              .github/use-case-tests/traffic-splitting/api.yml | kubectl apply -f -n tyk -
+              .github/use-case-tests/traffic-splitting/api.yml | kubectl apply -n tyk -f -
 
       - name: Create Key
         run: |
@@ -139,6 +133,38 @@ jobs:
           echo "✅ Tyk Key created: $KEY_ID"
           echo "key_id=$KEY_ID" >> $GITHUB_OUTPUT
 
-#      - name: Use the generated key
-#        run: |
-#          echo "The generated Tyk key is: ${{ steps.create_key.outputs.key_id }}"
+      - name: Test ${{ env.PRIMARY }} API
+        run: |
+          result=$(hey -n 1000 -H "Authorization: Bearer ${{ steps.create_key.outputs.key_id }}" "http://localhost:${{ env.PRIMARY_PORT }}/api/get")
+          echo "$result"
+
+          # Capture status code distribution (200s and 429s)
+          status_200=$(echo "$result" | grep -oP '\[200\] \K\d+')
+          status_429=$(echo "$result" | grep -oP '\[429\] \K\d+')
+
+          echo "${{ env.PRIMARY }} results - Status 200: $status_200"
+          echo "${{ env.PRIMARY }} results - Status 429: $status_429"
+
+          # Fail the job if less than 800 200s or too many 429s
+          if [ "$status_200" -lt 800 ]; then
+            echo "Test failed: Less than 800 successful requests (200s)."
+            exit 1
+          fi
+
+      - name: Test ${{ env.SECONDARY }} API
+        run: |
+          result=$(hey -n 1000 -H "Authorization: Bearer ${{ steps.create_key.outputs.key_id }}" "http://localhost:${{ env.SECONDARY_PORT }}/api/get")
+          echo "$result"
+
+          # Capture status code distribution (200s and 429s)
+          status_200=$(echo "$result" | grep -oP '\[200\] \K\d+')
+          status_429=$(echo "$result" | grep -oP '\[429\] \K\d+')
+
+          echo "${{ env.SECONDARY }} results - Status 200: $status_200"
+          echo "${{ env.SECONDARY }} results - Status 429: $status_429"
+
+          # Fail the job if less than 800 200s or too many 429s
+          if [ "$status_200" -lt 800 ]; then
+            echo "Test failed: Less than 800 successful requests (200s)."
+            exit 1
+          fi
